apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: gndf
  name: fe
  labels:
    app: "fe"
    version: {{ .Values.image_fe.tag }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "fe"
  template:
    metadata:
      labels:
        app: "fe"
        version: {{ .Values.image_fe.tag }}
    spec:
      containers:
      - name: gndf-web
        image: {{ .Values.image_fe.repository }}:{{ .Values.image_fe.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: PORT
          value: "{{ .Values.env_fe.PORT }}"
        - name: API_ENDPOINT
          value: "{{ .Values.env_fe.API_ENDPOINT }}"
        - name: API_CLIENTID
          value: "{{ .Values.env_fe.API_CLIENTID }}"
        - name: API_CLIENTSECRET
          value:  "{{ .Values.env_fe.API_CLIENTSECRET }}"
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: "/"
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/"
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 60
      nodeSelector:
        cloud.google.com/gke-nodepool: monitoring
