apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: gndf
  name: db
  labels:
    app: mongodb
    version: {{ .Values.image_db.tag }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
        version: {{ .Values.image_db.tag }}
    spec:
      containers:
      - name: gndf-mongodb
        image: "{{ .Values.image_db.repository }}:{{ .Values.image_db.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 27017
          - containerPort: 28017
        env:
          - name: MAX_RAM
            value: "{{ .Values.env_db.MAX_RAM}}"
        volumeMounts:
        - mountPath: /data/db
          name: db-data
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
      nodeSelector:
        cloud.google.com/gke-nodepool: db-workloads
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: gndf-pvc