{{- if .Values.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-default-cert
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  tls.crt: {{ .Values.ssl.defaultCert }}
  tls.key: {{ .Values.ssl.defaultKey }}
  {{- if and .Values.ssl.ehealth_gov_ua_cert .Values.ssl.ehealth_gov_ua_key }}
  ehealth_gov_ua_cert.crt: {{ .Values.ssl.ehealth_gov_ua_cert }}
  ehealth_gov_ua_key.key: {{ .Values.ssl.ehealth_gov_ua_key }}
  {{- end }}
  {{- if and .Values.ssl.ehealth_gov_ua_cert_2 .Values.ssl.ehealth_gov_ua_key_2 }}
  ehealth_gov_ua_cert_2.crt: {{ .Values.ssl.ehealth_gov_ua_cert_2 }}
  ehealth_gov_ua_key_2.key: {{ .Values.ssl.ehealth_gov_ua_key_2 }}
  {{- end }}
{{- end }}
