
## API ##
#Docker image and tag for api
image_api:
  repository: edenlabllc/otp_verification_api
  tag: "1.45.13"

env_api:
   # --- Phoenix---#
   #APP_PORT
  port: "4000"
  #APP_HOST
  host: ""
  #APP_SECRET_KEY
  secret: ""
  ERLANG_COOKIE: ""
  GATEWAY_ADAPTER: Mouth.IP2SMSAdapter
  SOURCE_NUMBER: "E-Health"
  GATEWAY_URL: ""
  GATEWAY_LOGIN: ""
  GATEWAY_PASSWORD: ""
  CODE_EXPIRATION_PERIOD_MINUTES: "15"
  GATEWAY_STATUS_URL: ""
    # Database
  DB_HOST: "db-svc"
  DB_PORT: "5432"
  DB_POOL_SIZE: "50"
    # App migrations
  DB_MIGRATE: "true"
resources_api:
  cpu: "10m"
  cpu_limit: "1"
  memory: "150Mi"
  memory_limit: "400Mi"



## DB ##
image_db:
  repository: nebo15/alpine-postgre
  tag: pglogical

env_db:
  app: "postgresql"
  version: "9.6"
  #DB_USER: API - POSTGRES_DB: DB
  POSTGRES_USER: "db"
  #DB_PASSWORD: API and DB
  POSTGRES_PASSWORD: ""
  PGDATA: "/var/lib/postgresql/data"
  #DB_NAME: API
  POSTGRES_DB: "verification"
  REPLICATOR_USER: "pghoard"
  REPLICATOR_PASSWORD: ""
  db_port: "5432"

resources_db:
  cpu: "50m"
  memory: "512Mi"
  limits_memory: "1Gi"
  storage: "50Gi"

rollingUpdate:
  maxSurge: "1"
  maxUnavailable: "1"

env: demo

deployNotification:
  enabled: false
  slackEndpoint:
  slackChannel:
  slackUsername:
  slackEmoji:
