apiVersion: v1
kind: Secret
metadata:
  namespace: ael
  name: gcs-secret
  labels:
    app: pghoard
    component: google-cloud-storage
type: Opaque
data:
  {{- if or (eq .Values.env "dev") (eq .Values.env "demo") }}
  sa.json: 
   {{ end }}