apiVersion: v1
kind: Service
metadata:
  namespace: mithril
  name: mithril-svc-traefik
  labels:
    app: fe
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: public
  selector:
    app: fe
  type: ClusterIP
