
## API ##
#Docker image and tag for api
image_api:
  repository: edenlabllc/ehealth
  tag: "8.7.0"

env_api:
   # --- Phoenix---#
   #APP_PORT
  port: "4000"
  #APP_HOST
  host: ""
  #APP_SECRET_KEY
  secret: ""
  ERLANG_COOKIE: ""
  GATEWAY_ADAPTER: Mouth.IP2SMSAdapter
        # Database
  DB_NAME: "il"
  DB_USER: "db"
  DB_PASSWORD: ""
  DB_HOST: "db-svc"
  DB_PORT: "5432"
  DB_POOL_SIZE: "50"
        # PRM Database
  PRM_DB_NAME: "prm"
  PRM_DB_USER: "db"
  PRM_DB_PASSWORD: ""
  PRM_DB_HOST: "db-svc.prm.svc.cluster.local"
  PRM_DB_PORT: "5432"
  PRM_DB_POOL_SIZE: "50"
          # EventManager Database
  EVENT_MANAGER_DB_NAME: "event_manager"
  EVENT_MANAGER_DB_USER: "db"
  EVENT_MANAGER_DB_PASSWORD: ""
  EVENT_MANAGER_DB_HOST: "db-svc.em.svc.cluster.local"
  EVENT_MANAGER_DB_PORT: "5432"
  EVENT_MANAGER_DB_POOL_SIZE: "50"
  EM_ENABLED: true
          # Blocks database
  BLOCK_DB_NAME: "blocks"
  BLOCK_DB_USER: "db"
  BLOCK_DB_PASSWORD: ""
  BLOCK_DB_HOST: "blocks-db-svc.ops.svc.cluster.local"
  BLOCK_DB_PORT: "5432"
  BLOCK_DB_POOL_SIZE: "50"
          # FRAUD database
  FRAUD_DB_NAME: "fraud"
  FRAUD_DB_USER: "db"
  FRAUD_DB_PASSWORD: ""
  FRAUD_DB_HOST: "db-svc.fraud.svc.cluster.local"
  FRAUD_DB_PORT: "5432"
  FRAUD_DB_POOL_SIZE: "50"
        # App migrations & seeds
  DB_MIGRATE: "true"
  DB_SEED: "true"
        # Endpoints
          # PRM
  PRM_ENDPOINT: "http://api-svc.prm/api"
  PRM_REQUEST_TIMEOUT: "30000"
          # MPI
  MPI_ENDPOINT: "http://api-svc.mpi"
  MPI_REQUEST_TIMEOUT: "30000"
          # UAddress
  UADDRESS_ENDPOINT: "http://api-svc.uaddresses"
  UADDRESS_REQUEST_TIMEOUT: "30000"
          # OTP
  OTP_VERIFICATION_ENDPOINT: "http://api-svc.verification"
  OTP_VERIFICATION_REQUEST_TIMEOUT: "30000"
          # OPS
  OPS_ENDPOINT: "http://api-svc.ops"
  OPS_REQUEST_TIMEOUT: "30000"
          # Report
  REPORT_ENDPOINT: "http://api-svc.reports"
  REPORT_REQUEST_TIMEOUT: "30000"
          # MAN
  MAN_ENDPOINT: "http://api-svc.man"
  MAN_REQUEST_TIMEOUT: "30000"
          # OAuth
  OAUTH_ENDPOINT: "http://api-svc.mithril"
  OAUTH_REQUEST_TIMEOUT: "30000"
          # Digital signature
  DIGITAL_SIGNATURE_ENDPOINT: "http://api-svc.digital-signature"
          # Casher
  CASHER_ENDPOINT: "http://casher-svc.il"
  CASHER_REQUEST_TIMEOUT: "30000"
          # Media storage
  MEDIA_STORAGE_ENDPOINT: "http://api-svc.ael"
  MEDIA_STORAGE_ENABLED: true
  MEDIA_STORAGE_LEGAL_ENTITY_BUCKET: "legal-entities-dev"
  MEDIA_STORAGE_DECLARATION_BUCKET: "declarations-dev"
  MEDIA_STORAGE_DECLARATION_REQUEST_BUCKET: "declaration-requests-dev"
  MEDIA_STORAGE_MEDICATION_REQUEST_REQUEST_BUCKET: "medication-request-requests-dev"
  MEDIA_STORAGE_CONTRACT_BUCKET: "contracts-dev"
  MEDIA_STORAGE_CONTRACT_REQUEST_BUCKET: "contract-requests-dev"
  MEDIA_STORAGE_PERSON_BUCKET: "persons-dev"
  MEDIA_STORAGE_RELATED_LEGAL_ENTITY_BUCKET: "related-legal-entities-dev"

          # Bamboo
  POSTMARK_ENDPOINT: ""
  POSTMARK_API_KEY: ""
          # employee request invitation
  BAMBOO_MAILER: Core.Bamboo.PostmarkMailer
  MAILGUN_API_KEY: ""
  MAILGUN_DOMAIN: ""
  BAMBOO_SMTP_SERVER: ""
  BAMBOO_SMTP_HOSTNAME: ""
  BAMBOO_SMTP_PORT: 587
  BAMBOO_SMTP_USERNAME: ""
  BAMBOO_SMTP_PASSWORD: ""
  BAMBOO_EMPLOYEE_REQUEST_INVITATION_FROM: ""
  BAMBOO_EMPLOYEE_REQUEST_INVITATION_SUBJECT: "Запрошення до співпраці з eHealth"
  EMPLOYEE_REQUEST_INVITATION_TEMPLATE_ID: "1"
  EMPLOYEE_REQUEST_INVITATION_TEMPLATE_FORMAT: "text/html"
  EMPLOYEE_REQUEST_INVITATION_TEMPLATE_LOCALE: "uk_UA"
  EMPLOYEE_REQUEST_UPDATE_INVITATION_TEMPLATE_ID: "7"
  EMPLOYEE_REQUEST_UPDATE_INVITATION_TEMPLATE_FORMAT: "text/html"
  EMPLOYEE_REQUEST_UPDATE_INVITATION_TEMPLATE_LOCALE: "uk_UA"
  BAMBOO_EMPLOYEE_REQUEST_UPDATE_INVITATION_FROM: ""
  BAMBOO_EMPLOYEE_REQUEST_UPDATE_INVITATION_SUBJECT: "Запрошення до співпраці з eHealth"
          # employee created notification
  BAMBOO_EMPLOYEE_CREATED_NOTIFICATION_FROM: ""
  BAMBOO_EMPLOYEE_CREATED_NOTIFICATION_SUBJECT: "Вас зареєстровано у медичному закладі"
  EMPLOYEE_CREATED_NOTIFICATION_TEMPLATE_ID: "2"
  EMPLOYEE_CREATED_NOTIFICATION_TEMPLATE_FORMAT: "text/html"
  EMPLOYEE_CREATED_NOTIFICATION_TEMPLATE_LOCALE: "uk_UA"
  DECLARATION_REQUEST_PRINTOUT_FORM_TEMPLATE_ID: "4"
  DECLARATION_REQUEST_PRINTOUT_FORM_TEMPLATE_FORMAT: "text/html"
  DECLARATION_REQUEST_PRINTOUT_FORM_TEMPLATE_LOCALE: "uk_UA"
        # Credentials recovery requests
  CREDENTIALS_RECOVERY_REQUEST_TTL: "1500"
  BAMBOO_CREDENTIALS_RECOVERY_REQUEST_INVITATION_FROM: ""
  BAMBOO_CREDENTIALS_RECOVERY_REQUEST_INVITATION_SUBJECT: "Посилання для відновлення доступу до порталу eHealth"
  CREDENTIALS_RECOVERY_REQUEST_INVITATION_TEMPLATE_ID: "5"
  CREDENTIALS_RECOVERY_REQUEST_INVITATION_TEMPLATE_FORMAT: "text/html"
  CREDENTIALS_RECOVERY_REQUEST_INVITATION_TEMPLATE_LOCALE: "uk_UA"
  # Email verification
  EMAIL_VERIFICATION_TEMPLATE_ID: ""
  EMAIL_VERIFICATION_FROM: ""
  EMAIL_VERIFICATION_SUBJECT: "Посилання для підтвердження електронної пошти для порталу eHealth"
  EMAIL_VERIFICATION_TEMPLATE_FORMAT: "text/html"
  EMAIL_VERIFICATION_TEMPLATE_LOCALE: "uk_UA"
  TOKENS_TYPES_PERSONAL: "MSP,PHARMACY"
  TOKENS_TYPES_MIS: "MIS"
  TOKENS_TYPES_ADMIN: "NHS ADMIN"
  DIGITAL_SIGNATURE_ENABLED: "true"
  CHAIN_VERIFICATION_FAILED_NOTIFICATION_FROM: ""
  CHAIN_VERIFICATION_FAILED_NOTIFICATION_TO: ""
  CHAIN_VERIFICATION_FAILED_NOTIFICATION_SUBJECT: ""
  CHAIN_VERIFICATION_FAILED_NOTIFICATION_ID: 6
  CHAIN_VERIFICATION_FAILED_NOTIFICATION_FORMAT: "text/html"
  CHAIN_VERIFICATION_FAILED_NOTIFICATION_LOCALE: "uk_UA"
  CIPHER_KEYPHRASE: ""
  CIPHER_IVPHRASE: ""
  OWNER_POSITIONS: "P1, P2, P3, P4, P5, P19"
  EMPLOYEE_REQUEST_AUTOTERMINATION_SCHEDULE: "* * * * *"
  DECLARATION_REQUEST_AUTOTERMINATION_SCHEDULE: "* * * * *"
  # Cabinet
  JWT_SECRET: ""
  JWT_TTL_EMAIL: "72"
  JWT_TTL_REGISTRATION: "15"
  CABINET_ROLE_ID: ""
  CABINET_CLIENT_ID: ""
  # Contract requests
  CONTRACT_REQUEST_PRINTOUT_FORM_TEMPLATE_ID: 9
  CONTRACT_REQUEST_PRINTOUT_FORM_APPENDIX_TEMPLATE_ID: 10
  CONTRACT_AUTOTERMINATION_SCHEDULE: "*/15 * * * *"
  # Deviation medication dispence
  DEVIATION: "0.01"
      #resources
resources_api:
  cpu: "10m"
  cpu_limit: "1"
  memory: "200Mi"
  memory_limit: "500Mi"


## DB ##
image_db:
  repository: nebo15/alpine-postgre
  tag: pglogical

env_db:
  app: "postgresql"
  version: "9.6"
  #DB_USER: API - POSTGRES_DB: DB
  POSTGRES_USER: "db"
  #DB_PASSWORD: API and DB
  POSTGRES_PASSWORD: ""
  PGDATA: "/var/lib/postgresql/data"
  #DB_NAME: API
  POSTGRES_DB: "il"
  REPLICATOR_USER: "pghoard"
  REPLICATOR_PASSWORD: ""
  db_port: "5432"

resources_db:
  cpu: "50m"
  memory: "512Mi"
  limits_memory: "1Gi"
  storage: "50Gi"

log_backups:
  enabled: true
  period_in_seconds: "30"
  image: google/cloud-sdk:198.0.0-alpine
  log_folder: /var/lib/postgresql/data/pg_log
  account:
  key_file_path:
  bucket:


rollingUpdate:
  maxSurge: "1"
  maxUnavailable: "1"

env: demo

deployNotification:
  enabled: false

## Cacher ##
image_casher:
  repository: edenlabllc/casher
  tag: "0.0.1"

resources_casher:
  cpu: "10m"
  cpu_limit: "1"
  memory: "100Mi"
  memory_limit: "200Mi"

env_casher:
  host: "http://casher-svc.il"
  port: "4000"
  SECRET_KEY: ""
  REDIS_HOST: "redis-master.redis.svc.cluster.local"
  REDIS_POOL_SIZE: "5"
  PERSON_DATA_TTL: "900"
