apiVersion: v1
kind: Service
metadata:
  namespace: ops
  name: blocks-db-svc
  labels:
    app: {{ .Values.env_blocks_db.app }}
spec:
  ports:
  - name: postgresql
    port: 5432
    targetPort: {{ .Values.env_blocks_db.port_name }}
  selector:
    app: {{ .Values.env_blocks_db.app }}
  type: ClusterIP
  clusterIP: "None"
