apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
  name: db-svc-nodeport
  namespace: fraud
spec:
  ports:
  - nodePort: 30010
    port: 30010
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgresql
  #sessionAffinity: None
  type: NodePort
