apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: uaddresses-admin-frontend
  namespace: uaddresses
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
       - path:
         backend:
          serviceName: uaddresses-svc-traefik
          servicePort: 80
