apiVersion: v1
kind: Service
metadata:
  namespace: uaddresses
  name: db-svc
  labels:
    app: postgresql
spec:
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: postgresql
  type: ClusterIP
  clusterIP: "None"
