apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: fe
  name: status
  labels:
    app: status
    version: {{ .Values.image_status.tag}}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: status
  template:
    metadata:
      labels:
        app: status
        version: {{ .Values.image_status.tag}}
    spec:
      containers:
      - name: annon-status-web
        image: {{ .Values.image_status.image}}:{{ .Values.image_status.tag}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: PORT
          value: "{{ .Values.STATUS_env.PORT}}"
        - name: API_ENDPOINT
          value: "{{ .Values.STATUS_env.API_ENDPOINT}}"
        - name: PROJECT_NAME
          value: "{{ .Values.STATUS_env.PROJECT_NAME}}"
        - name: PROJECT_DESCRIPTION
          value: "{{ .Values.STATUS_env.PROJECT_DESCRIPTION}}"
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            memory: "128Mi"
            cpu: "100m"
