apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: fe
  name: admin
  labels:
    app: admin
    version: {{ .Values.image_admin.tag}}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
        version: {{ .Values.image_admin.tag}}
    spec:
      containers:
      - name: fe-admin
        image: {{ .Values.image_admin.image}}:{{ .Values.image_admin.tag}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
             {{- if or (eq .Values.env "prod") (eq .Values.env "preprod") }}
        readinessProbe:
          httpGet:
            path: /sign-in/
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
             {{ end }}
        env:
        - name: PORT
          value:  "{{ .Values.admin_env.PORT}}"
        - name: API_HOST
          value:  "{{ .Values.admin_env.API_HOST}}"
        - name: CLIENT_ID
          value:  "{{ .Values.admin_env.CLIENT_ID}}"
        - name: CLIENT_SECRET
          value:  "{{ .Values.admin_env.CLIENT_SECRET}}"
        - name: OAUTH_REDIRECT_URL
          value:  "{{ .Values.admin_env.OAUTH_REDIRECT_URL}}"
        - name: OAUTH_URL
          value:  "{{ .Values.admin_env.OAUTH_URL}}"
        - name: APP_ENV
          value:  "{{ .Values.admin_env.APP_ENV}}"
        - name: BI_URL
          value:  "{{ .Values.admin_env.BI_URL}}"
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            memory: "128Mi"
            cpu: "100m"
        {{- if .Values.nodeSelector_fe }}
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.nodeSelector_fe}}
        {{ end }}
