apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: fe
  name: auth
  labels:
    app: auth
    version: {{ .Values.image_AUTH.tag}}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        version: {{ .Values.image_AUTH.tag}}
    spec:
      containers:
      - name: fe-auth
        image: {{ .Values.image_AUTH.image}}:{{ .Values.image_AUTH.tag}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
             {{- if or (eq .Values.env "prod") (eq .Values.env "preprod") }}
        readinessProbe:
          httpGet:
            path: /sign-in/
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
             {{ end }}
        env:
        - name: PORT
          value: "{{ .Values.AUTH_env.PORT}}"
        - name: API_ENDPOINT
          value: "{{ .Values.AUTH_env.API_ENDPOINT}}"
        - name: AUTH_ENDPOINT
          value: "{{ .Values.AUTH_env.AUTH_ENDPOINT}}"
        - name: CLIENT_ID
          value: "{{ .Values.AUTH_env.CLIENT_ID}}"
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            memory: "528Mi"
            cpu: "500m"
        {{- if .Values.nodeSelector_fe }}
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.nodeSelector_fe}}
        {{ end }}
