apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: fe
  name: iit-proxy-web
  labels:
    app: iit-proxy-web
    version: {{ .Values.image_iit_proxy_web.tag }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: iit-proxy-web
  template:
    metadata:
      labels:
        app: iit-proxy-web
        version: {{ .Values.image_iit_proxy_web.tag }}
    spec:
      containers:
      - name: fe-iit-proxy-web
        image: {{ .Values.image_iit_proxy_web.image }}:{{ .Values.image_iit_proxy_web.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.iit_proxy_web_env.PORT }}
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: {{ .Values.iit_proxy_web_env.PORT }}
          timeoutSeconds: 2
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: {{ .Values.iit_proxy_web_env.PORT }}
          timeoutSeconds: 2
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        {{- range $name, $value := .Values.iit_proxy_web_env }}
        {{- if not (empty $value) }}
        - name: {{ $name | quote }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            memory: "128Mi"
            cpu: "100m"
