apiVersion: v1
kind: Service
metadata:
  namespace: fe
  name: admin-svc-traefik
  labels:
    app: admin
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: public
  selector:
    app: admin
  type: ClusterIP
