apiVersion: v1
kind: Service
metadata:
  namespace: fe
  name: admin-svc
  labels:
    app: admin
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: public
{{- if or (eq .Values.env "prod") (eq .Values.env "preprod") }}
  - port: 443
    targetPort: 8080
    protocol: TCP
    name: public-https
  {{ end }}
  selector:
    app: admin
    {{- if or (eq .Values.env "dev") (eq .Values.env "demo") }}
  type: LoadBalancer
  loadBalancerIP: "{{ .Values.image_admin.loadBalancerIP }}"
    {{- else if or (eq .Values.env "prod") (eq .Values.env "preprod") }}
  type: NodePort
    {{ end }}