apiVersion: v1
kind: Service
metadata:
  namespace: fe
  name: status-svc
  labels:
    app: status
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: public
  selector:
    app: status
  type: LoadBalancer
  #loadBalancerIP: "{{ .Values.image_status.loadBalancerIP}}"
