apiVersion: v1
kind: Service
metadata:
  namespace: fe
  name: auth-web-svc
  labels:
    app: auth-web
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: public
  selector:
    app: auth-web
  type: ClusterIP
