        {{- if or  (eq .Values.env "demo") (eq .Values.env "denovo") (eq .Values.env "denovo-preprod")  }}
apiVersion: v1
kind: Service
metadata:
  namespace: fe
  name: auth-svc-traefik
  labels:
    app: auth
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: public
  selector:
    app: auth
  type: ClusterIP
    {{ end }}